# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: control_message.proto
# Protobuf Python Version: 4.25.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x63ontrol_message.proto\"|\n\x0e\x43ontrolMessage\x12)\n\x04type\x18\x01 \x01(\x0e\x32\x1b.ControlMessage.MessageType\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c\"1\n\x0bMessageType\x12\t\n\x05MEDIA\x10\x00\x12\t\n\x05\x43LOSE\x10\x01\x12\x0c\n\x08\x46INALIZE\x10\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'control_message_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_CONTROLMESSAGE']._serialized_start=25
  _globals['_CONTROLMESSAGE']._serialized_end=149
  _globals['_CONTROLMESSAGE_MESSAGETYPE']._serialized_start=100
  _globals['_CONTROLMESSAGE_MESSAGETYPE']._serialized_end=149
# @@protoc_insertion_point(module_scope)
