# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: transcription_event.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19transcription_event.proto\"\xb3\x02\n\x12TranscriptionEvent\x12+\n\x04type\x18\x01 \x01(\x0e\x32\x1d.TranscriptionEvent.EventType\x12\x12\n\ntranscript\x18\x02 \x01(\t\x12\x12\n\nstart_time\x18\x03 \x01(\x02\x12\x10\n\x08\x65nd_time\x18\x04 \x01(\x02\x12\x1d\n\x15vad_speech_start_time\x18\x05 \x01(\x02\x12\x19\n\x11speech_start_time\x18\x06 \x01(\x02\x12\x17\n\x0fspeech_end_time\x18\x07 \x01(\x02\x12\x10\n\x08is_final\x18\x08 \x01(\x08\"Q\n\tEventType\x12\x0e\n\nTRANSCRIPT\x10\x00\x12\n\n\x06\x43LOSED\x10\x01\x12\x14\n\x10VAD_SPEECH_START\x10\x02\x12\x12\n\x0eVAD_SPEECH_END\x10\x03\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'transcription_event_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _TRANSCRIPTIONEVENT._serialized_start=30
  _TRANSCRIPTIONEVENT._serialized_end=337
  _TRANSCRIPTIONEVENT_EVENTTYPE._serialized_start=256
  _TRANSCRIPTIONEVENT_EVENTTYPE._serialized_end=337
# @@protoc_insertion_point(module_scope)
